server:
  port: 8989
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
        default-filters:
          - RemoveRequestHeader=Cookie
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /api/v1/users/v3/api-docs
      - name: order-service
        url: /api/v1/orders/v3/api-docs
      - name: product-service
        url: /api/v1/products/v3/api-docs
