spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8091

feign:
  retryer:
    maxAttempts: 3
    period: 2000
    maxPeriod: 5000
  product:
    service:
      name: ${PRODUCT_SERVICE_NAME:product-service}
  user:
    service:
      name: ${USER_SERVICE_NAME:user-service}

      #      url: ${PRODUCT_SERVICE_URL:http://localhost:8092}
      #      path: ${PRODUCT_SERVICE_PATH:/api/v1/orders}