spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/products_db
#      uuid-representation: standard
server:
  port: 8092

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

