spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090
#  servlet:
#    context-path: /ecommerce/user/api