spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: cloud-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
        default-filters:
          - RemoveRequestHeader=Cookie
management:
  endpoints:
    web:
      exposure:
        include: "*"
